import{a as L,i as d}from"./assets/vendor-Cbhu4xvy.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function c(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=c(e);fetch(e.href,r)}})();async function u(o,t){const e=`https://pixabay.com/api/?key=42059071-0978dc0d7158b742eee7c30f5&q=${encodeURIComponent(o)}&image_type=photo&orientation=horizontal&safesearch=true`,r={page:t,per_page:13};return(await L.get(e,{params:r})).data}u();function v(o){const{largeImageURL:t,webformatURL:c,tags:n,likes:e,views:r,downloads:i,comments:b}=o;return`<a href="${t}" class="card">
      <li>
        <img src="${c}" alt="${n}" />
        <p><b>Views: </b>${r}</p>
        <p><b>Likes: </b>${e}</p>
        <p><b>Comments: </b>${b}</p>
        <p><b>Downloads: </b>${i}</p>
      </li>
    </a>`}function w(o){return o.map(v).join("")}const s={form:document.querySelector(".js-form"),gallery:document.querySelector(".js-gallery"),more:document.querySelector(".js-more"),loader:document.querySelector(".loader")};let l,a,m;s.form.addEventListener("submit",q);s.more.addEventListener("click",$);async function q(o){if(o.preventDefault(),y(),a=1,l=o.target.elements.query.value.trim(),!l){d.error({title:"Error!",message:"No query!",position:"center"}),p();return}s.gallery.innerHTML="";const t=await u(l,a);if(t.total===0){d.error({title:"Sorry",message:"No matches found for your search query.",position:"center"}),s.form.elements.query.value="";return}f(t.hits),m=Math.ceil(t.totalHits/13),g(),h(),o.target.reset()}async function $(){a+=1,y();const o=await u(l,a);f(o.hits),h(),g();const t=s.gallery.firstElementChild.getClientRects().height;scrollBy({behavior:"smooth",top:t*2})}function f(o){const t=w(o);s.gallery.insertAdjacentHTML("beforeend",t)}function E(){s.more.classList.remove("invisible")}function p(){s.more.classList.add("invisible")}function g(){a>=m?p():E()}function y(){s.loader.classList.remove("invisible")}function h(){s.loader.classList.add("invisible")}
//# sourceMappingURL=index.js.map
