import{a as L,i as d}from"./assets/vendor-Cbhu4xvy.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function c(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=c(e);fetch(e.href,t)}})();async function u(r,o){const e=`https://pixabay.com/api/?key=42059071-0978dc0d7158b742eee7c30f5&q=${encodeURIComponent(r)}&image_type=photo&orientation=horizontal&safesearch=true`,t={page:o,per_page:13};return(await L.get(e,{params:t})).data}u();function v(r){const{largeImageURL:o,webformatURL:c,tags:i,likes:e,views:t,downloads:n,comments:b}=r;return`<a href="${o}" class="card">
      <li>
        <img src="${c}" alt="${i}" />
        <p><b>Views: </b>${t}</p>
        <p><b>Likes: </b>${e}</p>
        <p><b>Comments: </b>${b}</p>
        <p><b>Downloads: </b>${n}</p>
      </li>
    </a>`}function w(r){return r.map(v).join("")}const s={form:document.querySelector(".js-form"),gallery:document.querySelector(".js-gallery"),more:document.querySelector(".js-more"),loader:document.querySelector(".loader")};let l,a,m;s.form.addEventListener("submit",q);s.more.addEventListener("click",$);async function q(r){if(r.preventDefault(),y(),a=1,l=r.target.elements.query.value.trim(),!l){d.error({title:"Error!",message:"No query!",position:"center"}),p();return}s.gallery.innerHTML="";const o=await u(l,a);if(o.total===0){d.error({title:"Sorry",message:"No matches found for your search query.",position:"center"}),s.form.elements.query.value="";return}f(o.hits),m=Math.ceil(o.totalHits/13),g(),h(),r.target.reset()}async function $(){a+=1,y();const r=await u(l,a);f(r.hits),h(),g()}function f(r){const o=w(r);s.gallery.insertAdjacentHTML("beforeend",o)}function I(){s.more.classList.remove("invisible")}function p(){s.more.classList.add("invisible")}function g(){a>=m?p():I()}function y(){s.loader.classList.remove("invisible")}function h(){s.loader.classList.add("invisible")}
//# sourceMappingURL=index.js.map
